### ISSUE TITLE
missing puts and question on csr_enum_array

### ISSUE THREAD

**Issue by wadester** [michaeljclark/riscv-probe#3]
I am new to RISCV but hope to work with it a lot more in the future.  I am trying to learn
the tools and build environment.  I am using Ubuntu 18 64-bit on Intel as a test platform
(and soon to try with Fedora 28).

As a test, I copied riscv-probe and made a very simple main.  It failed to build because 
puts was not defined (I guess printf("string") gets converted to puts("string").  I added:
    int puts(const char *s) {
        putstring(s);
    }

This built, but failed to run.  I needed to include csr_enum_array():
    qemu-system-riscv32 -nographic -machine spike_v1.10 -kernel build/bin/rv32/test2-spike 
    qemu-system-riscv32: Trying to execute code outside RAM or ROM at 0x80000000  
    This usually means one of the following happened:....

By defining puts and the csr_enum_array() my simple hello world program worked.

#include "femto.h"
int main()
{
    	int *csrenum = csr_enum_array();
	putstring("Test123\n");
	printf("Hello World\n");
	printf("\n");
}

**Comment by michaeljclark** [comment]
puts has been added. try the latest version

**Comment by michaeljclark** [comment]
Oh I saw your note about puts. I think there is a problem with the hello example on the spike machine. Thanks for the hint regards csr_enum_array. Looking into it...

**Comment by michaeljclark** [comment]
There is now several examples in the examples directory and the Makefile has been improved to automatically pick up new code.

To create a new example just create a new directory and add a rules.mk with progname_objs = program.o e.g.

```
$ cat examples/hello/rules.mk
hello_objs = hello.o
```

**Comment by michaeljclark** [comment]
Okay, it happened to be an interaction between the QEMU HTIF console driver in QEMU and the offset of the HTIF symbols in the executable (Note: `virt`, `sifive_e` and `sifive_u` were fine). I moved the HTIF section to the end of the linker script (`env/spike/default.lds`) and now the hello example works. You'll notice there is now `examples/hello/hello.c`. It's likely adding code fixed the issue by changing the size of the sections. It is possible that QEMU put HTIF IO memory over the top of `.bss` or the `.text` section.

```
$ qemu-system-riscv32 -nographic -machine spike_v1.10 -kernel build/bin/rv32/spike/hello
hello
$ qemu-system-riscv64 -nographic -machine spike_v1.10 -kernel build/bin/rv64/spike/hello
hello
```
